sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t diyor03/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true diyor03/docker-react npm run test
